name: cellpose
dependencies:
  - python=3.6
  - pip
  - mkl
  - numpy
  - scikit-image
  - numba
  - pyqt
  - scipy
  - matplotlib
  - pip:
    - mxnet-mkl
    - opencv_python
    - pyqtgraph
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose>=0.0.1.21
